/**
 * J3 permission matrix (docs/JOKKO-J3-DESIGN.md §3, rendered to
 * docs/JOKKO-J3-PERMISSION-MATRIX.md by scripts/authz-matrix.mjs).
 *
 * EVERY route in lib/api-router.js has exactly one policy here
 * (tests/j3/authz-matrix.test.js fails otherwise). The dispatcher enforces,
 * centrally and before the handler runs:
 *   - actor   the principal kind (user / admin / partner / webhook / cron / public)
 *   - perm    for admins: the operator permission (lib/authz/catalog.js)
 *   - role    an ACTIVE application role (driver, agent)
 *   - risk    'cash_out' → lib/authz/outbound-guard.js (recovery / credential /
 *             contact-change / new-device holds, step-up, tier)
 *             'sensitive_change' → trusted session + step-up + no recovery cool-off
 * The handler/service enforces the object-level `resource` relationship
 * (proven by tests/j3/horizontal-sweep.test.js) and the money rules (J2 kernel).
 *
 * resource vocabulary:
 *   self                caller's own account/wallet/profile only
 *   public              catalog / public profile data (minimal DTO)
 *   payer→counterparty  caller pays from own wallet to a named counterparty
 *   party               caller must be a party to the object (buyer, seller, rider, sender, recipient …)
 *   member / admin-of / creator / owner-of <x>   relationship to a group/business/event/thread
 *   business:<capability>  BUSINESS_CAPABILITIES in catalog.js (owner or active member with that role)
 *   partner_key         partner API key (scoped to its partner)
 *   signature           provider webhook signature
 *   cron_secret         CRON_SECRET bearer
 *   none                authentication bootstrap (rate-limited)
 */

const U = (perm, resource = 'self', extra = {}) => ({ actor: 'user', perm, resource, ...extra });
const A = (perm, extra = {}) => ({ actor: 'admin', perm, resource: 'operator_scope', ...extra });
const PUB = (perm, resource = 'none', extra = {}) => ({ actor: 'public', perm, resource, ...extra });
const PARTNER = (perm, extra = {}) => ({ actor: 'partner', perm, resource: 'partner_key', ...extra });
const HOOK = (provider) => ({ actor: 'webhook', perm: `webhook.${provider}`, resource: 'signature', audit: 'external_op' });
const CRON = (job) => ({ actor: 'cron', perm: `cron.${job}`, resource: 'cron_secret', audit: 'job' });

const MONEY = { audit: 'ledger+risk' };
const OUT = (extra = {}) => ({ ...MONEY, stepUp: 'amount', ...extra }); // internal outbound money
const CASH_OUT = { ...MONEY, risk: 'cash_out', stepUp: 'always', tier: 2 };
const SENSITIVE = { risk: 'sensitive_change', stepUp: 'always', audit: 'identity' };

export const ROUTE_POLICY = {
  // ── Public / bootstrap ────────────────────────────────────────────────────
  'GET health': PUB('ops.health.public'),
  'GET platform/config': PUB('platform.config.read', 'public'),
  'GET support/contact': PUB('support.contact.read', 'public'),
  'POST auth/phone': PUB('auth.otp.request', 'none', { audit: 'throttle' }),
  'POST auth/email': PUB('auth.otp.request', 'none', { audit: 'throttle' }),
  'POST auth/password/login': PUB('auth.password.login', 'none', { audit: 'session' }),
  'POST auth/password/set-with-otp': PUB('auth.password.reset', 'none', { audit: 'identity' }),
  'POST auth/recover': PUB('auth.recover.request', 'none', { audit: 'throttle' }),
  'POST auth/verify': PUB('auth.otp.verify', 'none', { audit: 'session+identity' }),
  'POST auth/refresh': PUB('auth.refresh', 'session_owner', { audit: 'session' }),

  // ── Session, device, credentials ──────────────────────────────────────────
  'POST auth/logout': U('auth.logout', 'session_owner', { audit: 'session' }),
  'POST auth/logout-all': U('auth.logout_all', 'self', { audit: 'session' }),
  'GET auth/sessions': U('auth.sessions.read'),
  'POST auth/sessions/:id/revoke': U('auth.sessions.revoke', 'session_owner', { audit: 'session' }),
  'GET auth/devices': U('auth.devices.read'),
  'POST auth/devices/:id/revoke': U('auth.devices.revoke', 'device_owner', { audit: 'identity' }),
  'POST auth/password/set': U('auth.password.set', 'self', SENSITIVE),
  'POST auth/complete-profile': U('profile.complete', 'self', { audit: 'identity' }),
  'POST auth/pin/set': U('auth.pin.set', 'self', { audit: 'identity', note: 'current PIN required to change; after recovery the fresh OTP session sets it' }),
  'POST auth/pin/verify': U('auth.pin.verify', 'self', { audit: 'throttle', note: 'grants session-bound step-up' }),
  'POST auth/pin/unlock': U('auth.pin.unlock', 'self', { audit: 'identity', note: 'unlock = recovery semantics (PIN reset + cool-off)' }),
  'POST auth/biometric': U('auth.biometric.toggle', 'self', SENSITIVE),
  'POST auth/device/verify': U('auth.device.verify', 'device_owner', { audit: 'identity' }),

  // ── Profile & contact ─────────────────────────────────────────────────────
  'GET me': U('profile.read'),
  'GET me/summary': U('profile.read'),
  'GET me/student-pass': U('profile.student_pass.read'),
  'POST me/student-pass': U('profile.student_pass.request'),
  'PATCH me': U('profile.update', 'self', { audit: 'identity', note: 'email is never set here; use me/email (verified)' }),
  'POST me/email': U('profile.email.request', 'self', SENSITIVE),
  'POST me/email/confirm': U('profile.email.confirm', 'self', SENSITIVE),
  'POST me/phone': U('profile.phone.request', 'self', SENSITIVE),
  'POST me/phone/confirm': U('profile.phone.confirm', 'self', SENSITIVE),
  'GET users/lookup': U('users.lookup', 'public', { note: 'minimal DTO; no phone/balance' }),
  'GET profiles/:id': U('profiles.read', 'public'),
  'POST roles/:id': U('roles.self_enable', 'self', { audit: 'identity', note: 'self-service roles only (promoter, seller, worker)' }),

  // ── KYC ───────────────────────────────────────────────────────────────────
  'GET kyc/status': U('kyc.status.read'),
  'POST kyc/cni/submit': U('kyc.submit', 'self', { audit: 'identity', note: 'submitted ≠ verified; provider or compliance decides' }),
  'POST kyc/address/submit': U('kyc.submit', 'self', { audit: 'identity' }),

  // ── Wallet & money movement (J2 kernel; object = caller's own wallet) ─────
  'GET wallet': U('wallet.read'),
  'GET money/home': U('wallet.read', 'self', { note: 'available / held / pending + allowed actions with user-safe reasons' }),
  'GET money/activity': U('wallet.history.read', 'self', { note: 'ledger-based history' }),
  'GET money/activity/:reference': U('wallet.receipt.read', 'party (the reference touches the caller’s accounts / own operation)'),
  'POST money/preview': U('wallet.preview', 'self', { note: 'server-authoritative amount / fee / total; executes nothing' }),
  'GET money/intents/:id': U('wallet.intent.read', 'self (own Idempotency-Key namespace)'),
  'POST money/charges': U('merchant.charge.create', 'business:business.charges.create', { audit: 'ledger' }),
  'GET money/charges/:id': U('merchant.charge.view', 'opaque code holder (server-provided merchant + amount only)'),
  'POST money/charges/:id/pay': U('merchant.charge.pay', 'payer (pays own wallet → merchant; once; before expiry; amount must match)', OUT({ tier: 1 })),
  'POST money/charges/:id/cancel': U('merchant.charge.cancel', 'business:business.charges.create'),
  'POST money/payments/:reference/refund': U('merchant.refund', 'payee of the original payment (or its business treasury)', MONEY),
  'GET transactions': U('wallet.history.read'),
  'GET kori/transactions': U('wallet.history.read'),
  'GET kori/reserve': U('reserve.public.read', 'public'),
  'POST kori/convert': U('wallet.convert', 'self', { ...CASH_OUT, note: 'disabled (410)' }),
  'POST transfers/send': U('transfer.send', 'payer→counterparty', OUT({ tier: 1 })),
  'POST transfers/:reference/undo': U('transfer.undo', 'party', OUT({ note: 'sender only, 60 s window' })),
  'POST transfers/request': U('transfer.request', 'self'),
  'GET transfers/requests': U('transfer.request.read', 'party'),
  'GET transfers/requests/:id': U('transfer.request.read', 'party'),
  'POST transfers/requests/:id/accept': U('transfer.request.pay', 'party', OUT({ tier: 1, note: 'payer only' })),
  'POST transfers/requests/:id/deny': U('transfer.request.deny', 'party'),
  'POST transfers/requests/:id/cancel': U('transfer.request.cancel', 'creator'),
  'POST cash/in': U('wallet.cash_in', 'self', { audit: 'external_op' }),
  'POST cash/out': U('wallet.cash_out', 'self', CASH_OUT),
  'POST deposits/national': U('wallet.beta_deposit', 'self', { audit: 'external_op', note: 'non-production only' }),
  'POST deposits/agent': U('wallet.agent_deposit', 'self', { audit: 'external_op' }),
  'GET deposits/agent/:reference': U('wallet.agent_deposit.read', 'party'),
  'POST withdrawals/agent': U('wallet.agent_withdraw', 'self', CASH_OUT),
  'GET withdrawals/agent/:reference': U('wallet.agent_withdraw.read', 'party'),
  'POST deposits/card/session': U('wallet.card_deposit', 'self', { audit: 'external_op' }),
  'GET deposits/card/:reference': U('wallet.card_deposit.read', 'party'),
  'POST merchants/:id/pay': U('merchant.pay', 'payer→counterparty', OUT({ tier: 1 })),
  'GET merchants/:id/public': U('merchant.public.read', 'public'),
  'GET merchant-vouchers/mine': U('voucher.read'),
  'GET payment-funds': U('fund.read'),
  'POST payment-funds': U('fund.create'),
  'POST payment-funds/:id/fund': U('fund.deposit', 'owner-of fund', MONEY),
  'POST payment-funds/:id/withdraw': U('fund.withdraw', 'owner-of fund', MONEY),
  'GET scheduled-payments': U('scheduled.read'),
  'POST scheduled-payments': U('scheduled.create', 'self', MONEY),
  'PATCH scheduled-payments/:id': U('scheduled.update', 'owner-of scheduled payment'),
  'POST offline/sync': U('offline.sync', 'self', OUT({ note: 'replays through the same guarded handlers' })),
  'GET invite/share': U('invite.read'),

  // ── Agents (customer side + agent side) ──────────────────────────────────
  'POST agent/apply': U('agent.apply', 'self', { audit: 'identity', note: 'creates a pending application only' }),
  'GET agent/application': U('agent.application.read'),
  'GET agents/nearby': U('agents.nearby.read', 'public'),
  'GET agent/me': U('agent.self.read', 'self', { role: 'agent' }),
  'PATCH agent/location': U('agent.self.update', 'self', { role: 'agent' }),
  'GET agent/payouts': U('agent.payouts.read', 'self', { role: 'agent' }),
  'POST agent/float/topup-request': U('agent.float.request', 'self', { role: 'agent' }),
  'GET agent/float/topup-requests/mine': U('agent.float.read', 'self', { role: 'agent' }),
  'POST agent/deposits/scan': U('agent.deposit.scan', 'agent-session', { role: 'agent', ...MONEY }),
  'POST agent/deposits/:id/confirm': U('agent.deposit.confirm', 'agent-session (this agent)', { role: 'agent', ...MONEY }),
  'POST agent/withdrawals/scan': U('agent.withdraw.scan', 'agent-session', { role: 'agent', ...MONEY }),
  'POST agent/withdrawals/:id/confirm': U('agent.withdraw.confirm', 'agent-session (this agent)', { role: 'agent', ...MONEY }),
  // ── J6 cash network (legacy QR session routes above answer 410 cash_flow_retired) ──
  'POST agent-cash/in': U('cash.in.create', 'self', { ...MONEY, note: 'intent only; no money until the agent completes' }),
  'POST agent-cash/out': U('cash.out.create', 'self', { ...CASH_OUT, note: 'risk + PIN + tier; funds held at creation' }),
  'GET agent-cash/tx': U('cash.tx.read', 'self'),
  'GET agent-cash/tx/:id': U('cash.tx.read', 'party (customer or the bound agent)'),
  'POST agent-cash/tx/:id/confirm': U('cash.tx.commit', 'customer of this transaction', { ...MONEY, note: 'cash-out: PIN step-up; binding hash must match' }),
  'POST agent-cash/tx/:id/cancel': U('cash.tx.cancel', 'customer of this transaction', { ...MONEY, note: 'only before the customer committed' }),
  'POST agent-cash/tx/:id/challenge': U('cash.tx.challenge', 'customer of this transaction', { note: 'only while unbound; old QR dies' }),
  'GET agent-cash/points': U('cash.points.read', 'public', { note: 'active service points; declared hours only; no float' }),
  'POST agent/cash/scan': U('agent.cash.scan', 'agent-session', { role: 'agent', ...MONEY, note: 'operating agent at an active service point' }),
  'POST agent/cash/:id/complete': U('agent.cash.complete', 'the bound agent', { role: 'agent', ...MONEY, note: 'agent PIN step-up' }),
  'POST agent/cash/:id/decline': U('agent.cash.decline', 'the bound agent', { role: 'agent', ...MONEY }),
  'GET agent/cash': U('agent.cash.read', 'self', { role: 'agent' }),
  'POST agent/cash-report': U('agent.cash_report', 'self', { role: 'agent', note: 'self-reported; never authoritative' }),
  'GET agent/commissions': U('agent.commissions.read', 'self', { role: 'agent' }),
  'POST agent/commissions/settle': U('agent.commissions.settle', 'self', { role: 'agent', ...MONEY }),
  'GET agent/lifecycle': U('agent.lifecycle.read', 'self'),
  'POST agent/service-points': U('agent.service_point.propose', 'organization owner', { note: 'pending until compliance approves' }),
  'PATCH agent/service-points/:id': U('agent.service_point.update', 'organization owner', { note: 'merchant assist only if permitted' }),
  'POST onboarding/assist': U('onboarding.assist.start', 'distribution rep (capability) or permitted service point', { audit: 'identity' }),
  'GET onboarding/assist/mine': U('onboarding.assist.read', 'self'),
  'POST onboarding/assist/open': U('onboarding.assist.open', 'merchant (code holder)'),
  'POST onboarding/assist/accept': U('onboarding.assist.accept', 'merchant (code holder, KYC tier 2)', { audit: 'identity', note: 'merchant becomes owner; introducer gets nothing' }),
  'POST onboarding/assist/decline': U('onboarding.assist.decline', 'merchant (code holder)'),

  // ── Courier / deliveries ─────────────────────────────────────────────────
  'GET drivers/profile': U('courier.profile.read'),
  'POST drivers/profile': U('courier.apply', 'self', { audit: 'identity', note: 'application; operator activates' }),
  'GET deliveries/nearby': U('delivery.open.read', 'courier', { role: 'driver' }),
  'GET deliveries/active/mine': U('delivery.mine.read', 'party'),
  'POST deliveries': U('delivery.create', 'self', MONEY),
  'GET deliveries/:id': U('delivery.read', 'party (buyer, assigned rider, or active courier for open jobs)'),
  'POST deliveries/:id/accept': U('delivery.accept', 'open job', { role: 'driver', ...MONEY }),
  'POST deliveries/:id/claim': U('delivery.accept', 'open job', { role: 'driver', ...MONEY }),
  'POST deliveries/:id/pickup': U('delivery.pickup', 'assigned rider', { role: 'driver' }),
  'POST deliveries/:id/deliver': U('delivery.deliver', 'assigned rider', { role: 'driver' }),
  'POST deliveries/:id/confirm': U('delivery.confirm', 'buyer', MONEY),
  'POST deliveries/:id/dispute': U('delivery.dispute', 'party'),
  'POST deliveries/:id/dispute/evidence': U('delivery.dispute.evidence', 'party'),
  'POST deliveries/:id/dispute/resolve': U('delivery.dispute.resolve', 'nobody (retired user route: always 403 operator_required — J8.0 P0 fix)'),

  // ── Workers / sellers ────────────────────────────────────────────────────
  'GET sellers/profile': U('seller.profile.read'),
  'POST sellers/profile': U('seller.profile.update', 'self', { audit: 'identity' }),
  'GET workers/profile': U('worker.profile.read'),
  'POST workers/profile': U('worker.profile.activate', 'self', { audit: 'identity', note: 'modes never grant courier/agent' }),
  'GET workers/receipts': U('worker.receipts.read'),
  'GET workers/credit-summary': U('worker.credit.read'),

  // ── Messaging (Mbolo) ────────────────────────────────────────────────────
  'GET mbolo/threads': U('messages.threads.read', 'member'),
  'POST mbolo/threads': U('messages.threads.create', 'self', { note: 'strangers land in message requests; blocks respected' }),
  'GET mbolo/threads/:id/messages': U('messages.read', 'member of thread'),
  'POST mbolo/threads/:id/messages': U('messages.send', 'member of thread (accepted, not blocked)'),
  'POST mbolo/threads/:id/charge-card': U('messages.charge_card', 'member of thread + business:business.charges.create of the charge; card carries the code only, amount from server'),
  'POST mbolo/threads/:id/members': U('messages.members.add', 'admin-of thread'),
  'GET mbolo/requests': U('messages.requests.read'),
  'POST mbolo/threads/:id/accept': U('messages.requests.accept', 'recipient of request'),
  'POST mbolo/threads/:id/decline': U('messages.requests.decline', 'recipient of request'),
  'POST mbolo/threads/:id/block': U('messages.block', 'member of thread', { audit: 'trust' }),
  'POST mbolo/threads/:id/report': U('messages.report', 'member of thread', { audit: 'trust' }),
  'POST mbolo/threads/:id/invite': U('messages.invite', 'admin-of thread'),
  'POST mbolo/join-group': U('messages.join', 'invite holder'),
  'POST mbolo/share': U('messages.share', 'member of target thread'),
  'POST mbolo/video/upload-token': U('media.upload'),
  'POST mbolo/broadcast': U('messages.broadcast', 'owner-of channel'),
  'GET mbolo/storage/status': U('media.read'),
  'POST mbolo/media/upload-url': U('media.upload'),
  'POST mbolo/media/complete': U('media.upload', 'owner-of asset'),
  'GET mbolo/vault': U('media.vault.read'),
  'DELETE mbolo/vault/:id': U('media.vault.delete', 'owner-of asset'),
  'GET mbolo/gifs': U('media.gifs.read', 'public'),
  'POST mbolo/gifs': U('media.gifs.create'),
  'POST mbolo/gifs/:id/use': U('media.gifs.use', 'public'),
  'POST mbolo/messages/:id/save': U('messages.save', 'member of thread'),
  'GET mbolo/threads/:id/presence': U('messages.presence.read', 'member of thread'),
  'POST mbolo/threads/:id/typing': U('messages.typing', 'member of thread'),
  'POST mbolo/threads/:id/read': U('messages.read_receipt', 'member of thread'),
  'GET mbolo/stories': U('stories.read', 'friends/contacts'),
  'POST mbolo/stories': U('stories.create'),
  'POST mbolo/device-keys': U('messages.device_keys.register', 'self'),

  // ── Social / trust ───────────────────────────────────────────────────────
  'GET friends': U('friends.read'),
  'POST friends': U('friends.request', 'self', { note: 'blocks respected' }),
  'DELETE friends/:id': U('friends.remove', 'self (removes only edges that include the caller)'),
  'GET friends/requests': U('friends.requests.read'),
  'POST friends/requests/:id/respond': U('friends.requests.respond', 'recipient of request'),
  'GET trust/blocks': U('trust.blocks.read'),
  'POST trust/block': U('trust.block', 'self', { audit: 'trust' }),
  'DELETE trust/block/:id': U('trust.unblock', 'owner-of block'),
  'POST trust/report': U('trust.report', 'self', { audit: 'trust' }),
  'GET trust/vouch': U('trust.vouch.read'),
  'POST trust/vouch': U('trust.vouch', 'self'),
  'POST calls/token': U('calls.token', 'member of thread'),
  'GET notifications/feed': U('notifications.read', 'self: own notifications; category filter; cursor pagination (J10)'),
  'GET notifications/unread': U('notifications.read', 'self: unread counts per category; muted categories not counted'),
  'POST notifications/read-all': U('notifications.update', 'self: own notifications only'),
  'GET me/community-settings': U('community.settings', 'self'),
  'PUT me/community-settings': U('community.settings', 'self: mutes (money/security never), phone discoverability, neighbourhood opt-in'),
  'GET me/today': U('community.today', 'self: own pending requests, orders, deliveries, work, school fees, tickets, tontine dues — read-only'),
  'GET notifications': U('notifications.read'),
  'POST notifications/:id/read': U('notifications.update', 'owner-of notification'),
  'GET sms/preferences': U('sms.preferences.read'),
  'POST sms/preferences': U('sms.preferences.update'),

  // ── Content / discovery ──────────────────────────────────────────────────
  'GET culture/feed': U('feed.read', 'public'),
  'GET trending/feed': U('feed.read', 'public'),
  'GET trending/alerts/:id': U('feed.read', 'public'),
  'POST trending/alerts/:id/read': U('feed.read_receipt', 'self'),
  'POST trending/alerts/:id/share': U('feed.share', 'self'),
  'GET charts': U('charts.read', 'public'),
  'POST charts/submit': U('charts.submit'),
  'POST charts/vote': U('charts.vote'),
  'GET charts/search': U('charts.read', 'public'),
  'GET geo/search': U('geo.search', 'public'),
  'POST polls': U('polls.ask', 'self (profile poll)'),
  'POST polls/:id/vote': U('polls.vote', 'public (profile poll; the vote is the caller’s own)'),
  'GET channels': U('channels.read', 'public'),
  'GET channels/mine': U('channels.mine.read'),
  'POST channels/mine': U('channels.mine.update', 'owner-of channel'),
  'GET channels/feed': U('channels.feed.read'),
  'POST channels/posts': U('channels.post', 'owner-of channel'),
  'POST channels/posts/:id/delete': U('channels.post.delete', 'owner-of post'),
  'GET channels/:id': U('channels.read', 'public'),
  'POST channels/:id/follow': U('channels.follow'),

  // ── Events / tickets / Jekkal ────────────────────────────────────────────
  'GET events': U('events.read', 'public'),
  'POST events': U('events.create', 'self', { note: 'promoter role is self-service' }),
  'GET events/mine': U('events.mine.read', 'creator'),
  'GET tickets/mine': U('tickets.read'),
  'POST tickets/check-in': U('tickets.check_in', 'creator of the ticket\'s event'),
  'POST events/:id/tickets': U('tickets.buy', 'payer→counterparty', OUT({ tier: 1 })),
  'POST events/:id/check-in': U('tickets.check_in', 'creator of event'),
  'GET events/:id/scan-stats': U('events.stats.read', 'creator of event'),
  'GET jekkal/campaigns': U('jekkal.read', 'public'),
  'POST jekkal/campaigns': U('jekkal.create'),
  'GET jekkal/campaigns/mine': U('jekkal.mine.read', 'creator'),
  'GET jekkal/campaigns/:id': U('jekkal.read', 'public (minimal)'),
  'POST jekkal/campaigns/:id/contribute': U('jekkal.contribute', 'payer→counterparty', OUT({ tier: 1 })),

  // ── Tontine ──────────────────────────────────────────────────────────────
  'GET tontine/groups': U('tontine.read', 'member'),
  'POST tontine/groups': U('tontine.create'),
  'GET tontine/groups/:id': U('tontine.read', 'member of group'),
  'POST tontine/groups/:id/accept': U('tontine.accept', 'invitee'),
  'POST tontine/groups/:id/decline': U('tontine.decline', 'invitee'),
  'POST tontine/groups/:id/leave': U('tontine.leave', 'member of group'),
  'POST tontine/groups/:id/invite': U('tontine.invite', 'creator of group'),
  'POST tontine/groups/:id/remove': U('tontine.remove', 'creator of group'),
  'POST tontine/groups/:id/start': U('tontine.start', 'creator of group'),
  'POST tontine/groups/:id/contribute': U('tontine.contribute', 'member of group (explicit consent)', OUT()),
  'POST tontine/groups/:id/release': U('tontine.release', 'creator of group (rule-based recipient)', MONEY),
  'POST tontine/groups/:id/cancel': U('tontine.cancel', 'creator of group', MONEY),

  // ── Affiliate / marketplace / commerce ──────────────────────────────────
  'GET affiliate/me': U('affiliate.read'),
  'POST affiliate/me': U('affiliate.enroll'),
  'GET affiliate/links': U('affiliate.links.read'),
  'POST affiliate/links': U('affiliate.links.create'),
  'GET affiliate/resolve/:code': U('affiliate.resolve', 'public'),
  'POST affiliate/links/:code/click': U('affiliate.click', 'public'),
  'POST affiliate/mbolo-share': U('affiliate.share'),
  'POST affiliate/earnings/payout': U('affiliate.earnings.payout', 'self: own earned deferred commissions, not under review → own wallet (inactive unless AFFILIATE_DEFERRED_SETTLEMENT)', MONEY),
  'GET products': U('products.read', 'public'),
  'POST products': U('products.create', 'business:business.catalog.manage'),
  'GET marketplace/search': U('marketplace.read', 'public'),
  'GET marketplace/shops/nearby': U('marketplace.read', 'public'),
  'GET marketplace/shops/:id': U('marketplace.read', 'public'),
  'GET marketplace/hubs': U('marketplace.read', 'public'),
  'POST marketplace/orders': U('marketplace.order', 'payer→counterparty', OUT({ tier: 1 })),
  'GET marketplace/orders/mine': U('marketplace.orders.read', 'buyer'),
  'GET marketplace/orders/merchant': U('marketplace.orders.merchant', 'business:business.read'),
  'GET marketplace/catalog/mine': U('marketplace.catalog.read', 'business:business.read'),
  'PATCH marketplace/products/:id': U('products.update', 'business:business.catalog.manage'),
  'DELETE marketplace/products/:id': U('products.delete', 'business:business.catalog.manage'),
  'POST marketplace/products/:id/view': U('products.view', 'public'),
  'GET marketplace/analytics': U('marketplace.analytics', 'business:business.read'),
  'PATCH marketplace/business/:id/settings': U('business.settings', 'business:business.admin'),
  'GET marketplace/orders/:id': U('marketplace.order.read', 'party (buyer or seller business member)'),
  'PATCH marketplace/orders/:id/status': U('marketplace.order.status', 'business:business.orders.fulfill (J5 state machine)'),
  'POST marketplace/orders/:id/confirm': U('marketplace.order.confirm', 'buyer', MONEY),
  'POST marketplace/orders/:id/cancel': U('marketplace.order.cancel', 'buyer (before the merchant starts; system-authorized full refund)', MONEY),

  // ── Distribution / B2B trade ─────────────────────────────────────────────
  'POST distribution/brand/register': U('distribution.register', 'business:business.admin'),
  'GET distribution/brand/mine': U('distribution.read', 'business:business.read'),
  'GET distribution/trade-accounts': U('trade.accounts.read', 'business:business.read'),
  'POST distribution/trade-accounts': U('trade.accounts.upsert', 'business:business.treasury'),
  'GET distribution/buyer-portal': U('trade.portal.read', 'business:business.read'),
  'GET distribution/buyer-portal/catalog': U('trade.portal.read', 'business:business.read'),
  'GET distribution/receivables': U('trade.receivables.read', 'business:business.wallet.read'),
  'GET distribution/invoices/mine': U('trade.invoices.read', 'party (buyer)'),
  'GET distribution/invoices/supplier': U('trade.invoices.read', 'business:business.wallet.read'),
  'POST distribution/invoices/:id/pay': U('trade.invoice.pay', 'party (buyer; business:business.pay)', OUT()),
  'POST distribution/invoices/:id/dispute': U('trade.invoice.dispute', 'party (buyer)'),
  'POST distribution/invoices/:id/dispute-resolve': U('trade.invoice.resolve', 'party (supplier business:business.treasury)', MONEY),
  'GET distribution/trade-summary': U('trade.summary.read', 'business:business.read'),

  // ── Hubs / parcels ───────────────────────────────────────────────────────
  'GET hubs/parcels/mine': U('parcels.read', 'party'),
  'POST hubs/parcels': U('parcels.create'),
  'GET hubs/parcels/origins': U('parcels.origins.read', 'public'),
  'GET hubs/parcels/:id': U('parcels.read', 'party'),
  'POST hubs/parcels/:id/in-transit': U('parcels.update', 'hub operator (business member of the hub)'),
  'POST hubs/parcels/:id/arrive': U('parcels.update', 'operator of the ACTIVE pickup point running this hub (J8.0; couriers/workers are not hub operators)'),
  'POST hubs/parcels/:id/last-mile': U('parcels.update', 'hub operator (business member of the hub)'),
  'POST hubs/parcels/:id/pickup': U('parcels.release', 'pickup-point operator releases on the code presented by the owner (J8.0; the owner cannot self-confirm; 5 wrong codes lock)'),

  // ── Businesses (KEBU) ────────────────────────────────────────────────────
  'GET businesses': U('businesses.read', 'public'),
  'GET businesses/mine': U('businesses.mine.read', 'member'),
  'GET businesses/:id': U('businesses.read', 'public (minimal) / member (full)'),
  'POST businesses': U('businesses.create', 'self', { tier: 3, audit: 'identity' }),
  'POST businesses/:id/status': U('business.status.post', 'business:business.admin'),
  'POST businesses/:id/community-status': U('business.community_status', 'business affiliate'),
  'GET businesses/:id/wallet': U('business.wallet.read', 'business:business.wallet.read'),
  'GET businesses/:id/credit-summary': U('business.credit.read', 'business:business.wallet.read'),
  'POST businesses/:id/transfer': U('business.transfer', 'business:business.treasury', OUT()),
  'GET businesses/:id/members': U('business.members.read', 'business:business.read'),
  'POST businesses/:id/members': U('business.members.invite', 'business:business.members.manage', { audit: 'identity' }),
  'GET businesses/invitations/mine': U('business.invitations.read', 'invitee'),
  'POST businesses/:id/members/:subId/accept': U('business.members.accept', 'invitee', { audit: 'identity' }),
  'POST businesses/:id/members/:subId/remove': U('business.members.remove', 'business:business.members.manage (or self-leave)', { audit: 'identity' }),
  'POST businesses/:id/members/:subId/role': U('business.members.role', 'business:business.members.manage (level + owner-only rules, never own role)', { audit: 'identity' }),
  // J5 Merchant + Business OS — every handler re-checks the business capability.
  'GET businesses/:id/os/access': U('business.os.access', 'business member (own capabilities)'),
  'GET businesses/:id/os/profile': U('business.os.profile.read', 'business:business.read'),
  'PATCH businesses/:id/os/profile': U('business.os.profile.write', 'business:business.profile.manage', { audit: 'identity' }),
  'POST businesses/:id/os/locations': U('business.os.location.create', 'business:business.profile.manage'),
  'PATCH businesses/:id/os/locations/:subId': U('business.os.location.update', 'business:business.profile.manage'),
  'POST businesses/:id/os/settlement': U('business.os.settlement', 'business owner only (one-way to business wallet)', { audit: 'identity' }),
  'POST businesses/:id/os/verification': U('business.os.verification.request', 'business owner only', { audit: 'identity' }),
  'GET businesses/:id/os/catalog': U('business.os.catalog.read', 'business:business.read'),
  'POST businesses/:id/os/catalog': U('business.os.catalog.create', 'business:business.catalog.manage'),
  'PATCH businesses/:id/os/catalog/:subId': U('business.os.catalog.update', 'business:business.catalog.manage (stock refused here)'),
  'POST businesses/:id/os/stock/:subId/adjust': U('business.os.stock.adjust', 'business:business.inventory.adjust (reason required, in-tx authority)', { audit: 'stock_movement' }),
  'GET businesses/:id/os/stock/:subId/history': U('business.os.stock.history', 'business:business.catalog.manage | business.inventory.adjust'),
  'GET businesses/:id/os/orders': U('business.os.orders.read', 'business:business.orders.read'),
  'GET businesses/:id/os/orders/:subId': U('business.os.order.read', 'business:business.orders.read (order of this business)'),
  'POST businesses/:id/os/orders/:subId/status': U('business.os.order.fulfil', 'business:business.orders.fulfill (locked state machine)'),
  'POST businesses/:id/os/orders/:subId/cancel': U('business.os.order.cancel', 'business:business.orders.cancel (full refund, in-tx authority)', MONEY),
  'POST businesses/:id/os/orders/:subId/refund': U('business.os.order.refund', 'business:business.refund (full refund, in-tx authority)', MONEY),
  'GET businesses/:id/os/money': U('business.os.money.read', 'business:business.activity.read | business.wallet.read (payroll / treasury lines by capability)'),
  'GET businesses/:id/os/analytics': U('business.os.analytics', 'business:business.analytics.read'),
  'GET businesses/:id/os/customers': U('business.os.customers', 'business:business.customers.read (name/handle + history with this business only)'),
  'GET businesses/:id/os/today': U('business.os.today', 'business member (each block by capability)'),
  'GET businesses/:id/os/charges': U('business.os.charges', 'business:business.charges.read (payer identity not shown)'),
  // J5 economic-OS contracts
  'POST businesses/:id/os/operating-mode': U('business.os.operating_mode', 'business owner only', { audit: 'identity' }),
  'GET businesses/:id/distribution/territories': U('distribution.territories.read', 'business:business.distribution.invite (distribution mode)'),
  'POST businesses/:id/distribution/territories': U('distribution.territories.create', 'business:business.distribution.manage (distribution mode)'),
  'GET businesses/:id/distribution/relationships': U('distribution.relationships.read', 'business:business.distribution.invite (reps: own introductions only)'),
  'POST businesses/:id/distribution/relationships': U('distribution.relationships.invite', 'business:business.distribution.invite — invitation grants NO access to the merchant'),

  // ── J7 B2B commerce & distribution ──────────────────────────────────────
  'GET businesses/:id/b2b/listings': U('b2b.listings.read', 'business:business.catalog.manage (seller)'),
  'POST businesses/:id/b2b/listings': U('b2b.listings.manage', 'business:business.catalog.manage (seller, distribution mode)'),
  'POST businesses/:id/b2b/price-lists': U('b2b.price_lists.manage', 'business:business.distribution.manage (seller)'),
  'GET businesses/:id/b2b/relationships': U('b2b.relationships.read', 'business:business.distribution.invite (reps: introduced or assigned only)'),
  'POST businesses/:id/b2b/relationships/:subId/configure': U('b2b.relationships.configure', 'business:business.distribution.manage — price list / rep are operational, never a data grant'),
  'POST businesses/:id/b2b/territories/:subId/reps': U('b2b.territories.reps', 'business:business.distribution.manage — territory is operational, never security authority'),
  'GET businesses/:id/b2b/depots/:subId/stock': U('b2b.depot.read', 'business:business.orders.read (seller depot)'),
  'POST businesses/:id/b2b/depots/:subId/stock': U('b2b.depot.adjust', 'business:business.inventory.adjust (seller depot; adjust needs a reason)', { audit: 'stock_movement' }),
  'GET businesses/:id/b2b/depots/:subId/movements': U('b2b.depot.read', 'business:business.orders.read (seller depot)'),
  'GET businesses/:id/b2b/analytics': U('b2b.analytics.read', 'business:business.distribution.manage | business.analytics.read (own trade only)'),
  'GET businesses/:id/b2b/rep-summary': U('b2b.rep.summary', 'business:business.distribution.invite (own book, counts only)'),
  'GET businesses/:id/b2b/suppliers': U('b2b.restock.read', 'business:business.purchasing (buyer)'),
  'GET businesses/:id/b2b/suppliers/:subId/catalog': U('b2b.catalog.read', 'business:business.purchasing + active relationship (wholesale_catalog)'),
  'GET businesses/:id/b2b/suppliers/:subId/reorder': U('b2b.reorder.read', 'business:business.purchasing + active relationship; suggestions only, never an order'),
  'POST businesses/:id/b2b/quote': U('b2b.quote', 'business:business.purchasing + active relationship; server price'),
  'GET businesses/:id/b2b/purchase-orders': U('b2b.po.read', 'business:business.purchasing (buyer side) | business.orders.read (seller side)'),
  'POST businesses/:id/b2b/purchase-orders': U('b2b.po.submit', 'business:business.purchasing (+ business.pay for a Net term) + active relationship; server price, expected total', { ...MONEY }),
  'GET businesses/:id/b2b/purchase-orders/:subId': U('b2b.po.read', 'party (buyer business: purchasing; seller business: orders.read)'),
  'POST businesses/:id/b2b/purchase-orders/:subId/accept': U('b2b.po.accept', 'party:seller business.orders.fulfill | distribution.manage', { audit: 'po_event' }),
  'POST businesses/:id/b2b/purchase-orders/:subId/reject': U('b2b.po.reject', 'party:seller business.orders.fulfill | distribution.manage', { audit: 'po_event' }),
  'POST businesses/:id/b2b/purchase-orders/:subId/pay': U('b2b.po.pay', 'party:buyer business.pay (business wallet → seller)', OUT({ stepUp: 'always' })),
  // ── J8 logistics (lib/logistics/*): object-level custody / party checks in the service ──
  'GET logistics/shipments/mine': U('logistics.shipment.read', 'self: shipments addressed to me (area-level view)'),
  'POST logistics/shipments/:id/respond': U('logistics.assignment.respond', 'active assigned courier; before pickup; decline returns it to dispatch', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/failure/respond': U('logistics.failure.respond', 'party on the claimed failure side (receiver | source); once', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/emergency-reassign': U('logistics.shipment.emergency_reassign', 'business:business.fleet.dispatch of the fulfiller (own fleet); reason; new courier holds nothing until handoff', { audit: 'shipment_event+identity' }),
  'POST logistics/shipments/:id/handoff-code': U('logistics.handoff.code', 'previous custodian courier | business:business.fleet.dispatch (own fleet); bound to the new courier', { audit: 'custody_challenge' }),
  'POST logistics/shipments/:id/handoff': U('logistics.handoff.accept', 'new active courier + handoff code; custody moves once', { audit: 'shipment_event' }),
  'GET businesses/:id/logistics/routes/:subId/reconciliation': U('logistics.routes.read', 'business:business.fleet.dispatch; own route'),
  'GET businesses/:id/b2b/product-mappings': U('b2b.mapping.read', 'business:business.inventory.adjust (buyer)'),
  'POST businesses/:id/b2b/product-mappings': U('b2b.mapping.write', 'business:business.inventory.adjust (buyer); supplier product bought by this buyer; own tracked product', { audit: 'stock' }),
  'POST businesses/:id/b2b/unmatched-receipts/:subId/resolve': U('b2b.mapping.resolve', 'business:business.inventory.adjust (buyer); own receipt; once', { audit: 'stock' }),
  'POST admin/logistics/shipments/:id/failure/rule': A('logistics.exceptions.resolve', { audit: 'admin+identity' }),
  'POST admin/logistics/shipments/:id/emergency-reassign': A('logistics.dispatch', { audit: 'admin+identity' }),
  'POST admin/logistics/shipments/:id/handoff-code': A('logistics.dispatch', { audit: 'custody_challenge' }),
  'POST logistics/shipments/batch/codes': U('logistics.code.issue', 'per item: party:source of that shipment; ≤ 60 items; each item counts against the dispatch budget (D42)', { audit: 'custody_challenge' }),
  'POST businesses/:id/b2b/purchase-orders/batch': U('b2b.po.advance', 'per item: party:seller business.orders.fulfill | distribution.manage; ≤ 60 items (D42)', { audit: 'po_event' }),
  'GET logistics/shipments/:id': U('logistics.shipment.read', 'party: source | receiver | active courier | dispatcher | pickup point (role-shaped DTO; precise destination only to the active courier)'),
  'GET logistics/courier/shipments': U('logistics.courier.read', 'self: own active assignments'),
  'GET businesses/:id/logistics/shipments': U('logistics.business.read', 'business:business.orders.read (origin) | business.purchasing (destination)'),
  'POST logistics/shipments/:id/ready': U('logistics.shipment.ready', 'party:source business.orders.fulfill', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/assign': U('logistics.shipment.assign', 'business:business.fleet.dispatch of the fulfiller; courier holds business.fleet.drive; courier ≠ receiver', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/unassign': U('logistics.shipment.assign', 'business:business.fleet.dispatch of the fulfiller; before pickup only', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/codes': U('logistics.code.issue', 'party: source (pickup / return) | receiver (delivery / collection); code bound to the assigned courier', { audit: 'custody_challenge' }),
  'POST logistics/shipments/:id/pickup': U('logistics.custody.pickup', 'active assigned courier + source-issued single-use code', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/step': U('logistics.custody.step', 'active assigned courier', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/deliver': U('logistics.custody.deliver', 'active assigned courier + receiver-issued single-use code', { ...MONEY, audit: 'shipment_event+ledger' }),
  'POST logistics/shipments/:id/fail': U('logistics.custody.fail', 'active assigned courier', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/exception': U('logistics.custody.exception', 'active assigned courier (claim only — never a delivery)', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/return/start': U('logistics.custody.return', 'active assigned courier', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/return/complete': U('logistics.custody.return', 'active assigned courier + source-issued single-use code', { ...MONEY, audit: 'shipment_event+ledger+stock' }),
  'POST logistics/shipments/:id/receiving': U('logistics.receiving.record', 'party:receiver business.purchasing; never the courier; once per shipment', { ...MONEY, audit: 'receiving_record+stock' }),
  'POST logistics/shipments/:id/drop': U('logistics.pickup_point.drop', 'operator of the ACTIVE pickup point on the request', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/release': U('logistics.pickup_point.release', 'releasing desk (source or pickup point operator) + receiver-issued code; never the receiver', { audit: 'shipment_event' }),
  'POST logistics/shipments/:id/cancel': U('logistics.shipment.cancel', 'party:source business.orders.fulfill; before pickup only', { ...MONEY, audit: 'shipment_event+ledger' }),
  'POST logistics/shipments/:id/dispute': U('logistics.dispute.open', 'party: source | receiver | courier; once per shipment; window 7 days', { audit: 'dispute' }),
  'GET logistics/disputes/:id': U('logistics.dispute.read', 'party to the disputed shipment'),
  'POST logistics/disputes/:id/evidence': U('logistics.dispute.evidence', 'party to the disputed shipment; append-only', { audit: 'dispute' }),
  'GET logistics/earnings': U('logistics.earnings.read', 'self: own courier earnings'),
  'POST logistics/earnings/payout': U('logistics.earnings.payout', 'self: own releasable earnings → own wallet', { ...MONEY, audit: 'ledger' }),
  'GET logistics/pickup-points': U('logistics.pickup_points.read', 'public: name / services / hours only'),
  'GET businesses/:id/logistics/transfers': U('logistics.transfers.read', 'business:business.orders.read'),
  'POST businesses/:id/logistics/transfers': U('logistics.transfers.create', 'business:business.inventory.adjust; both locations of this business', { audit: 'stock' }),
  'GET businesses/:id/logistics/routes': U('logistics.routes.read', 'business:business.fleet.dispatch'),
  'POST businesses/:id/logistics/routes': U('logistics.routes.create', 'business:business.fleet.dispatch; own ready shipments; driver holds business.fleet.drive', { audit: 'shipment_event' }),
  'POST businesses/:id/pickup-points': U('logistics.pickup_point.apply', 'business:business.profile.manage', { audit: 'identity' }),
  'GET admin/logistics/shipments': A('logistics.read'),
  'POST admin/logistics/shipments/:id/accept': A('logistics.dispatch', { audit: 'shipment_event' }),
  'POST admin/logistics/shipments/:id/assign': A('logistics.dispatch', { audit: 'shipment_event' }),
  'POST admin/logistics/shipments/:id/unassign': A('logistics.dispatch', { audit: 'shipment_event' }),
  'POST admin/logistics/shipments/:id/cancel': A('logistics.dispatch', { ...MONEY, audit: 'shipment_event+ledger' }),
  'POST admin/logistics/shipments/:id/rule': A('logistics.exceptions.resolve', { ...MONEY, audit: 'admin+identity+ledger' }),
  'GET admin/logistics/disputes': A('logistics.read'),
  'POST admin/logistics/disputes/:id/resolve': A('logistics.disputes.resolve', { audit: 'admin+identity; money reversal via maker/checker (logistics.disputes.reverse)' }),
  'POST admin/pickup-points/:id/decide': A('pickup_points.approve', { audit: 'admin+identity' }),
  // ── J9 Work & Opportunity (lib/work/*): object-level party / business checks in the service ──
  'GET work/types': U('work.types.read', 'public'),
  'GET work/profile': U('work.profile.read'),
  'PUT work/profile': U('work.profile.update', 'self', { audit: 'none', note: 'worker-entered only; no protected-attribute fields exist' }),
  'POST work/qualifications': U('work.qualification.add', 'self', { note: 'self_declared until an operator verifies' }),
  'POST work/blocks': U('work.block', 'self', { note: 'withdraws pending offers (escrow refunded) and invitations' }),
  'GET work/opportunities': U('work.discover', 'public: open postings of verified businesses; worker-chosen filters; newest first', { note: 'no paid ranking, no profiling' }),
  'GET work/opportunities/:id': U('work.discover', 'public (open; not from a business the caller blocked)'),
  'POST work/opportunities/:id/apply': U('work.apply', 'self; age / minor rules; never into a business the caller runs'),
  'GET work/applications': U('work.applications.read'),
  'POST work/applications/:id/withdraw': U('work.applications.withdraw', 'party: the applicant'),
  'GET work/offers': U('work.offers.read'),
  'POST work/offers/:id/accept': U('work.offer.accept', 'party: the offered worker; exact termsHash; funded if prepaid; age attestation', { audit: 'ledger' }),
  'POST work/offers/:id/decline': U('work.offer.decline', 'party: the offered worker', MONEY),
  'GET work/assignments': U('work.assignments.read'),
  'GET work/assignments/:id': U('work.assignments.read', 'party: the worker'),
  'POST work/assignments/:id/attendance': U('work.attendance.submit', 'party: the worker + business-issued single-use code', { audit: 'work_evidence' }),
  'POST work/assignments/:id/submit': U('work.milestone.submit', 'party: the worker; evidence required', { audit: 'work_evidence' }),
  'POST work/assignments/:id/end': U('work.assignment.end', 'party: the worker; before submitting work; unearned escrow back to the business', MONEY),
  'POST work/assignments/:id/disputes': U('work.dispute.open', 'party: the worker (nonpayment / terms / harassment / other)', { audit: 'work_evidence' }),
  'POST work/assignments/:id/feedback': U('work.feedback.leave', 'party: the worker; once; after work'),
  'GET work/disputes/:id': U('work.dispute.read', 'party (roles and content only)'),
  'POST work/disputes/:id/evidence': U('work.dispute.evidence', 'party; append-only', { audit: 'work_evidence' }),
  'POST work/disputes/:id/appeal': U('work.dispute.appeal', 'party who did not win; once; within the appeal window (money waits)', { audit: 'work_evidence' }),
  'GET work/earnings': U('work.earnings.read', 'self (J8 courier earnings shown read-only, never duplicated)'),
  'POST work/earnings/payout': U('work.earnings.payout', 'self: own releasable earnings, not frozen by a dispute → own wallet', MONEY),
  'GET work/feedback': U('work.feedback.read', 'self: feedback about me'),
  'POST work/feedback/:id/contest': U('work.feedback.contest', 'subject of the feedback'),
  'GET businesses/:id/work/opportunities': U('work.business.read', 'business:business.staffing.manage'),
  'POST businesses/:id/work/opportunities': U('work.opportunity.create', 'business:business.staffing.manage; verified business; fee-language postings held for review'),
  'POST businesses/:id/work/opportunities/:subId/status': U('work.opportunity.status', 'business:business.staffing.manage'),
  'GET businesses/:id/work/opportunities/:subId/applicants': U('work.applicants.read', 'business:business.staffing.manage; worker card only (no phone, age, nationality, language, photo)'),
  'POST businesses/:id/work/opportunities/:subId/invite': U('work.invite', 'business:business.staffing.manage; discoverable workers only; blocked = not found'),
  'POST businesses/:id/work/applications/:subId/decide': U('work.applicants.decide', 'business:business.staffing.manage'),
  'GET businesses/:id/work/workers': U('work.workers.search', 'business:business.staffing.manage; discoverable profiles only'),
  'POST businesses/:id/work/offers': U('work.offer.create', 'business:business.staffing.manage (+ business.pay to fund a prepaid offer)', OUT({ note: 'prepaid offers are funded into escrow when sent' })),
  'POST businesses/:id/work/offers/:subId/withdraw': U('work.offer.withdraw', 'business:business.staffing.manage; while sent', MONEY),
  'GET businesses/:id/work/assignments': U('work.business.read', 'business:business.staffing.manage'),
  'GET businesses/:id/work/assignments/:subId': U('work.business.read', 'business:business.staffing.manage; own assignment'),
  'POST businesses/:id/work/assignments/:subId/attendance-code': U('work.attendance.code', 'business:business.staffing.manage; own active assignment', { audit: 'work_challenge' }),
  'POST businesses/:id/work/assignments/:subId/accept': U('work.milestone.accept', 'business:business.staffing.manage; never the worker themself', MONEY),
  'POST businesses/:id/work/milestones/accept-batch': U('work.milestone.accept', 'per item: business:business.staffing.manage on that assignment; never the worker themself; ≤ 50 items; counts once on the account limiter + per item on the work_accept budget (A6/D42)', MONEY),
  'POST work/assignments/:id/evidence/files': U('work.evidence.file.upload', 'self: the worker of the assignment; sniffed type JPEG/PNG/WebP/PDF ≤ 1 MB; metadata stripped; ≤ 20 per assignment, ≤ 30/day (A6)', { audit: 'work_evidence' }),
  'GET work/assignments/:id/evidence/files': U('work.evidence.file.read', 'self: the worker of the assignment; metadata only'),
  'GET work/evidence/files/:id': U('work.evidence.file.read', 'self: the worker of the assignment; private, no-store; every read audited (WorkEvidenceAccess)', { audit: 'work_evidence_access' }),
  'POST businesses/:id/work/assignments/:subId/evidence/files': U('work.evidence.file.upload', 'business:business.staffing.manage on that assignment (A6)', { audit: 'work_evidence' }),
  'GET businesses/:id/work/assignments/:subId/evidence/files': U('work.evidence.file.read', 'business:business.staffing.manage on that assignment; metadata only'),
  'GET businesses/:id/work/evidence/files/:subId': U('work.evidence.file.read', 'business:business.staffing.manage on the file’s assignment; every read audited', { audit: 'work_evidence_access' }),
  'POST admin/work/evidence/files/:id/view': A('work.disputes.resolve', { audit: 'admin+identity; only files on a disputed assignment; reason required; every read audited' }),
  'POST businesses/:id/work/assignments/:subId/end': U('work.assignment.end', 'business:business.staffing.manage; no unilateral end once work is attended / submitted', MONEY),
  'POST businesses/:id/work/assignments/:subId/disputes': U('work.dispute.open', 'business:business.staffing.manage (false completion within the window; unpaid only)', { audit: 'work_evidence' }),
  'POST businesses/:id/work/assignments/:subId/feedback': U('work.feedback.leave', 'business:business.staffing.manage; once; after work'),
  'POST businesses/:id/work/disputes/:subId/evidence': U('work.dispute.evidence', 'business:business.staffing.manage; party', { audit: 'work_evidence' }),
  'POST businesses/:id/work/disputes/:subId/appeal': U('work.dispute.appeal', 'business:business.staffing.manage; party who did not win; once; within the appeal window', { audit: 'work_evidence' }),
  'GET businesses/:id/work/rules': U('work.rules.read', 'business:business.staffing.manage | business.pay'),
  'POST businesses/:id/work/rules': U('work.rules.propose', 'business:business.distribution.manage (rep) | business.staffing.manage (pickup fee); amount defaults to 0'),
  'POST businesses/:id/work/rules/:subId/approve': U('work.rules.approve', 'business:business.pay; a DIFFERENT member than the proposer', { audit: 'identity' }),
  'POST businesses/:id/work/rules/:subId/fund': U('work.rules.fund', 'business:business.pay; prefunded budget', OUT()),
  'POST businesses/:id/work/rules/:subId/end': U('work.rules.end', 'business:business.pay; unused budget back to the business', MONEY),
  'GET admin/work/review': A('work.review'),
  'POST admin/work/opportunities/:id/review': A('work.review', { audit: 'admin+identity' }),
  'POST admin/work/qualifications/:id/review': A('work.qualifications.verify', { audit: 'admin+identity' }),
  'GET admin/work/disputes': A('work.read'),
  'POST admin/work/disputes/:id/resolve': A('work.disputes.resolve', { audit: 'admin+identity; money via maker/checker (work.disputes.settle)' }),
  'POST admin/work/disputes/:id/appeal/resolve': A('work.disputes.resolve', { audit: 'admin+identity; a different operator than the first ruling; money via a new maker/checker approval' }),
  'GET admin/work/feedback': A('work.read'),
  'POST admin/work/feedback/:id/rule': A('work.feedback.rule', { audit: 'admin+identity' }),
  'GET cron/work': CRON('work'),
  'POST cron/work': CRON('work'),
  'GET cron/affiliate-settlement': CRON('affiliate-settlement'),
  'POST cron/affiliate-settlement': CRON('affiliate-settlement'),
  'GET cron/logistics': CRON('logistics'),
  'POST cron/logistics': CRON('logistics'),

  'POST businesses/:id/b2b/purchase-orders/:subId/advance': U('b2b.po.advance', 'party:seller business.orders.fulfill | distribution.manage; delivery recorded by seller unless a tracked J8 shipment carries the order', { audit: 'po_event' }),
  'POST businesses/:id/b2b/purchase-orders/:subId/buyer': U('b2b.po.receive', 'party:buyer business.purchasing (receive / complete / dispute)', { audit: 'po_event' }),
  'POST businesses/:id/b2b/purchase-orders/:subId/resolve': U('b2b.po.resolve', 'party:seller business.orders.fulfill | distribution.manage', { audit: 'po_event' }),
  'POST businesses/:id/b2b/purchase-orders/:subId/cancel': U('b2b.po.cancel', 'party: buyer business.purchasing (before acceptance) | seller business.orders.cancel (refund needs business.refund)', { ...MONEY }),
  'POST businesses/:id/b2b/purchase-orders/:subId/returns': U('b2b.returns.request', 'party:buyer business.purchasing; quantities ≤ ordered', { audit: 'return' }),
  'GET businesses/:id/b2b/invoices': U('b2b.invoices.read', 'business:business.purchasing (buyer) | business.orders.read (seller)'),
  'GET businesses/:id/b2b/invoices/:subId': U('b2b.invoices.read', 'party (buyer / supplier business)'),
  'POST businesses/:id/b2b/invoices/:subId/pay': U('b2b.invoices.pay', 'party:buyer business.pay (business wallet → supplier)', OUT({ stepUp: 'always' })),
  'POST businesses/:id/b2b/invoices/:subId/credit-memos': U('b2b.invoices.credit_memo', 'party:supplier business.refund — correction is a record, principal never rewritten', { audit: 'ledger' }),
  'GET businesses/:id/b2b/returns': U('b2b.returns.read', 'business:business.purchasing (buyer) | business.orders.read (seller)'),
  'POST businesses/:id/b2b/returns/:subId/decide': U('b2b.returns.decide', 'party:seller business.orders.fulfill | distribution.manage', { audit: 'return' }),
  'POST businesses/:id/b2b/returns/:subId/ship': U('b2b.returns.ship', 'party:buyer business.purchasing', { audit: 'return' }),
  'POST businesses/:id/b2b/returns/:subId/receive': U('b2b.returns.receive', 'party:seller business.orders.fulfill | distribution.manage; restock only on goods received', { audit: 'stock_movement' }),
  'POST businesses/:id/b2b/returns/:subId/resolve': U('b2b.returns.resolve', 'party:seller business.refund (credit memo / refund ≤ paid)', { ...MONEY }),
  'GET businesses/:id/os/relationships': U('merchant.relationships.read', 'business:business.relationships.manage'),
  'POST businesses/:id/os/relationships/:subId/respond': U('merchant.relationships.respond', 'business:business.relationships.manage (merchant side accepts)'),
  'POST businesses/:id/os/relationships/:subId/end': U('relationships.end', 'either side: business.relationships.manage | business.distribution.manage'),
  'GET me/distribution-invitations': U('distribution.invitations.mine', 'self (assisted onboarding)'),
  'POST me/distribution-invitations/:id/respond': U('distribution.invitations.respond', 'invited person; attaches a business they OWN'),
  'GET businesses/:id/os/payments': U('business.os.payments', 'business:business.charges.read | business.activity.read'),
  'POST businesses/:id/os/sales/manual': U('business.os.sales.manual', 'business:business.charges.create — off-ledger record, never Jokko money'),
  'GET commerce/capabilities': U('commerce.capabilities', 'any user (ACTIVE / DORMANT catalogue)'),
  'GET addresses': U('addresses.mine', 'self'),
  'POST addresses': U('addresses.create', 'self, or business:business.profile.manage; homes never public'),
  'GET addresses/:id': U('addresses.view', 'owner full; business members; delivery fulfilment roles for an active order; otherwise coarse area only'),
  'POST businesses/:id/os/integrations/link-code': U('integrations.link_code', 'business owner only'),
  'GET businesses/:id/os/integrations': U('integrations.list', 'business:business.profile.manage'),
  'POST businesses/:id/os/integrations/:subId/revoke': U('integrations.revoke', 'business owner only', { audit: 'identity' }),
  'GET businesses/:id/reviews': U('business.reviews.read', 'public'),
  'POST businesses/:id/reviews': U('business.reviews.create', 'verified customer'),
  'GET businesses/:id/kebu-score': U('business.score.read', 'business:business.read'),
  'GET businesses/:id/payroll/groups': U('payroll.read', 'business:business.pay'),
  'POST businesses/:id/payroll/groups': U('payroll.manage', 'business:business.pay'),
  'GET businesses/:id/payroll/employees': U('payroll.read', 'business:business.pay'),
  'POST businesses/:id/payroll/employees': U('payroll.manage', 'business:business.pay'),
  'POST businesses/:id/payroll/pay': U('payroll.pay', 'business:business.pay', OUT()),
  'POST businesses/:id/payroll/run': U('payroll.pay', 'business:business.pay', OUT()),
  'GET businesses/:id/school/students': U('school.read', 'business:business.admin'),
  'POST businesses/:id/school/students': U('school.manage', 'business:business.admin'),
  'GET businesses/:id/school/periods': U('school.read', 'business:business.admin'),
  'POST businesses/:id/school/periods': U('school.manage', 'business:business.admin'),
  'GET businesses/:id/school/periods/:subId/status': U('school.read', 'business:business.admin'),
  'POST businesses/:id/school/pay': U('school.fee.pay', 'payer→counterparty (parent)', OUT({ tier: 1 })),
  'POST businesses/:id/school/remind': U('school.remind', 'business:business.admin'),
  'GET businesses/:id/cooperative/deliveries': U('coop.read', 'business:business.admin'),
  'POST businesses/:id/cooperative/deliveries': U('coop.log', 'member (logs own delivery)'),
  'POST businesses/:id/cooperative/deliveries/:subId/verify': U('coop.verify', 'business:business.admin'),
  'POST businesses/:id/cooperative/payout': U('coop.payout', 'business:business.pay', OUT()),

  // ── Support (user side) ──────────────────────────────────────────────────
  'GET support/tickets/mine': U('support.tickets.mine'),
  'POST support/tickets': U('support.tickets.create'),
  'GET support/tickets/:id': U('support.tickets.read', 'owner-of ticket'),
  'POST support/tickets/:id/reply': U('support.tickets.reply', 'owner-of ticket'),

  // ── Webhooks (signature) ─────────────────────────────────────────────────
  'POST webhooks/julaya': HOOK('julaya'),
  'POST webhooks/stripe': HOOK('stripe'),
  'POST webhooks/kyc/smile': { ...HOOK('kyc_smile'), audit: 'identity', note: 'freshness + one-time receipt + job/user binding' },
  'POST webhooks/kyc/sumsub': { ...HOOK('kyc_sumsub'), audit: 'identity', note: 'body digest + one-time receipt' },
  'POST webhooks/sms/inbound': HOOK('sms_inbound'),

  // ── Partner API (per-partner API key) ────────────────────────────────────
  'POST v1/checkout/sessions': PARTNER('partner.checkout'),
  'POST v1/payments/collect': PARTNER('partner.collect', { audit: 'external_op' }),
  'GET v1/payments/:reference': PARTNER('partner.payment.read'),
  'POST v1/payments/:reference/sandbox-complete': PARTNER('partner.sandbox', { note: 'non-production only' }),
  'POST v1/messages/send': PARTNER('partner.messages.send'),
  'GET v1/pay/:id': PUB('partner.pay_page.read', 'payment link holder'),
  'POST v1/pay/:id/confirm': PUB('partner.pay_page.confirm', 'payment link holder + user auth inside', { audit: 'ledger' }),
  'POST v1/pos/sessions': PARTNER('partner.pos'),
  'GET v1/pos/:reference': PARTNER('partner.pos.read'),
  'POST v1/payouts': PARTNER('partner.payout', { audit: 'external_op', note: 'submitted payouts → provider reconciliation / admin review (D9)' }),
  'POST v1/business-links': PARTNER('partner.business_link', { note: 'consented link: owner one-time code + partner key' }),
  'GET v1/payouts/:reference': PARTNER('partner.payout.read'),
  'POST v1/payouts/:reference/sandbox-complete': PARTNER('partner.sandbox', { note: 'non-production only' }),
  'POST v1/support/agents': PARTNER('partner.support.agents'),
  'GET v1/support/agents': PARTNER('partner.support.agents'),
  'POST v1/support/threads': PARTNER('partner.support.threads'),
  'GET v1/support/threads': PARTNER('partner.support.threads'),
  'POST v1/support/threads/:id/assign': PARTNER('partner.support.threads'),
  'POST v1/support/threads/:id/messages': PARTNER('partner.support.threads'),

  // ── Cron (CRON_SECRET) ───────────────────────────────────────────────────
  'GET cron/daily': CRON('daily'),
  'POST cron/daily': CRON('daily'),
  'GET cron/scheduled-payments': CRON('scheduled_payments'),
  'POST cron/scheduled-payments': CRON('scheduled_payments'),
  'GET cron/financial-integrity': CRON('financial_integrity'),
  'POST cron/financial-integrity': CRON('financial_integrity'),
  'GET cron/pending-transactions': CRON('pending_transactions'),
  'POST cron/pending-transactions': CRON('pending_transactions'),
  'GET cron/fraud-monitor': CRON('fraud_monitor'),
  'POST cron/fraud-monitor': CRON('fraud_monitor'),
  'GET cron/tontine-processor': CRON('tontine_processor'),
  'POST cron/tontine-processor': CRON('tontine_processor'),
  'GET cron/rider-status': CRON('rider_status'),
  'POST cron/rider-status': CRON('rider_status'),
  'GET cron/daily-financial-report': CRON('daily_financial_report'),
  'POST cron/daily-financial-report': CRON('daily_financial_report'),
  'GET cron/delivery-auto-release': CRON('delivery_auto_release'),
  'POST cron/delivery-auto-release': CRON('delivery_auto_release'),
  'GET cron/agent-cash-sweep': CRON('agent_cash_sweep'),
  'POST cron/agent-cash-sweep': CRON('agent_cash_sweep'),
  'GET cron/agent-monthly-payout': CRON('agent_monthly_payout'),
  'POST cron/agent-monthly-payout': CRON('agent_monthly_payout'),

  // ── Operator authentication ──────────────────────────────────────────────
  'POST admin/auth/bootstrap': PUB('admin.bootstrap', 'bootstrap secret, only while no operator exists', { audit: 'identity' }),
  'POST admin/auth/login': PUB('admin.login', 'none', { audit: 'admin' }),
  'POST admin/auth/setup-2fa': PUB('admin.totp.setup', 'challenge token'),
  'POST admin/auth/confirm-2fa': PUB('admin.totp.confirm', 'challenge token', { audit: 'admin' }),
  'POST admin/auth/verify-2fa': PUB('admin.totp.verify', 'challenge token', { audit: 'admin' }),
  'POST admin/auth/logout': A(null, { note: 'any authenticated operator' }),
  'GET admin/me': A(null, { note: 'own roles and permissions' }),

  // ── Operator console (separation of duties) ──────────────────────────────
  'GET admin/dashboard': A('ops.dashboard.read'),
  'GET admin/ops/health': A('ops.health.read'),
  'GET admin/held-transactions': A('risk.held.read'),
  'POST admin/held-transactions/:id/approve': A('risk.held.decide', { audit: 'admin+risk' }),
  'POST admin/held-transactions/:id/reject': A('risk.held.decide', { audit: 'admin+risk' }),
  'GET admin/fraud-alerts': A('risk.alerts.read'),
  'POST admin/fraud-alerts/:id/ack': A('risk.alerts.ack', { audit: 'admin' }),
  'GET admin/transactions/:id': A('money.transactions.read'),
  'POST admin/users/:id/freeze': A('users.freeze', { audit: 'admin+identity', note: 'protective: single operator' }),
  'POST admin/users/:id/unfreeze': A('users.unfreeze.request', { audit: 'admin+identity', note: 'maker-checker (user_unfreeze)' }),
  'POST admin/users/:id/credentials/invalidate': A('users.credentials.invalidate', { audit: 'admin+identity', note: 'protective: single operator' }),
  'POST admin/rails/:id/release': A('finance.rails.release', { audit: 'admin+ledger' }),
  'POST admin/refunds': A('finance.refund', { audit: 'admin+ledger', note: '≤ MONEY_REFUND_SINGLE_MAX_KORI single; above → maker-checker (support_refund)' }),
  'GET admin/support-tickets': A('support.tickets.read'),
  'GET admin/support-tickets/:id': A('support.tickets.read'),
  'POST admin/support-tickets/:id': A('support.tickets.write', { audit: 'admin' }),
  'PATCH admin/support-tickets/:id': A('support.tickets.write', { audit: 'admin' }),
  'GET admin/reports/daily': A('finance.reports.read'),
  'GET admin/agents': A('agents.read'),
  'POST admin/agents': A('agents.onboard', { audit: 'admin+identity', note: 'no initial float here (finance tops up separately)' }),
  'GET admin/agents/reconcile': A('agents.read', { note: 'read-only report' }),
  'POST admin/agents/reconcile': A('finance.position.read', { audit: 'admin', note: 'records exceptions; corrects nothing' }),
  'GET admin/agents/liquidity': A('agents.read', { note: 'ledger float; physical cash self-reported' }),
  'GET admin/agents/:id/overview': A('agents.read', { note: 'support-safe inspection' }),
  'POST admin/agents/:id/verify-identity': A('agents.onboard', { audit: 'admin+identity', note: 'requires applicant KYC tier ≥ 2' }),
  'POST admin/agents/:id/activate': A('agents.onboard', { audit: 'identity', note: 'maker-checker agent_activation (approve: agents.activate, different operator)' }),
  'POST admin/agents/:id/terminate': A('agents.manage', { audit: 'admin+identity' }),
  'POST admin/agents/:id/service-point': A('agents.manage', { audit: 'identity', note: 'same organization only' }),
  'POST admin/agents/:id/adopt': A('agents.onboard', { audit: 'admin+identity', note: 'legacy agent → J6 org + PENDING point; activates nothing' }),
  'POST admin/service-points/:id/status': A('agents.onboard', { audit: 'identity' }),
  'POST admin/service-points/:id/merchant-assist': A('agents.manage', { audit: 'identity' }),
  'POST admin/cash/:id/resolve': A('risk.held.decide', { audit: 'identity', note: 'maker-checker agent_cash_resolve (approve: finance.adjust.approve)' }),
  'POST admin/cash/:id/risk-decision': A('risk.held.decide', { audit: 'admin+ledger', note: 'risk_hold only: resume or return funds to owner' }),
  'GET admin/agents/commission-rules': A('finance.position.read'),
  'POST admin/agents/commission-rules': A('finance.commission.propose', { audit: 'admin' }),
  'POST admin/agents/commission-rules/:id/activate': A('finance.commission.propose', { audit: 'identity', note: 'maker-checker (approve: finance.commission.approve)' }),
  'POST admin/agents/commission-budget/fund': A('finance.adjust.request', { audit: 'identity', note: 'maker-checker treasury funding' }),
  'POST admin/agents/commissions/:id/clawback': A('risk.held.decide', { audit: 'identity', note: 'maker-checker; unsettled only' }),
  'POST admin/agents/:id/float': A('finance.agent_float', { audit: 'admin+ledger', note: '≤ AGENT_FLOAT_SINGLE_MAX_XOF single; above → maker-checker (agent_float_topup)' }),
  'POST admin/agents/:id/approve': A('agents.onboard', { audit: 'admin+identity', note: 'review decision; operator ≠ identity verifier; does NOT activate' }),
  'POST admin/agents/:id/reject': A('agents.onboard', { audit: 'admin+identity' }),
  'POST admin/agents/:id/suspend': A('agents.suspend', { audit: 'admin+identity' }),
  'GET admin/agent-float-requests': A('finance.agent_float'),
  'POST admin/agent-float-requests/:id/approve': A('finance.agent_float', { audit: 'admin+ledger', note: 'same caps as admin/agents/:id/float' }),
  'POST admin/agent-float-requests/:id/reject': A('finance.agent_float', { audit: 'admin' }),
  'PATCH admin/agents/:id': A('agents.manage', { audit: 'admin+identity', note: 'limits only; status changes via approve/suspend' }),
  'GET admin/audit-logs': A('audit.read'),
  'GET admin/users': A('users.search', { note: 'minimal DTO' }),
  'GET admin/users/:id': A('users.read', { note: 'sensitive fields only with users.read.sensitive' }),
  'GET admin/kyc/queue': A('kyc.review'),
  'POST admin/kyc/:id/approve': A('kyc.review', { audit: 'admin+identity' }),
  'POST admin/kyc/:id/reject': A('kyc.review', { audit: 'admin+identity' }),
  'POST admin/kyc/address/approve': A('kyc.review', { audit: 'admin+identity' }),
  'GET admin/distributors': A('distributors.read'),
  'GET admin/distributors/:id': A('distributors.read'),
  'PATCH admin/distributors/:id': A('distributors.manage', { audit: 'admin' }),
  'GET admin/support/stats': A('support.calls'),
  'GET admin/support/calls': A('support.calls'),
  'POST admin/support/calls': A('support.calls', { audit: 'admin' }),
  'GET admin/money/position': A('finance.position.read'),
  'GET admin/money/exceptions': A('finance.position.read'),
  'POST admin/money/statements': A('finance.statements.import', { audit: 'admin+ledger' }),
  'GET admin/money/adjustments': A('finance.position.read'),
  'POST admin/money/adjustments': A('finance.adjust.request', { audit: 'admin+ledger', note: 'D10: low-risk single path or dual authorization' }),
  'POST admin/money/adjustments/:id/approve': A('finance.adjust.approve', { audit: 'admin+ledger' }),
  'POST admin/money/adjustments/:id/reject': A('finance.adjust.approve', { audit: 'admin' }),
  'GET admin/partner-payments/held': A('finance.position.read'),
  'POST admin/partner-payments/:id/release': A('finance.adjust.request', { audit: 'admin+ledger', note: 'J6.0: release only to the business bound at creation, mapping + merchant active' }),
  'POST admin/partner-payments/:id/release/approve': A('finance.adjust.approve', { audit: 'admin+ledger', note: 'dual authorization; constrained adjustment' }),
  'POST admin/couriers/:id/approve': A('couriers.onboard', { audit: 'admin+identity' }),
  'POST admin/couriers/:id/suspend': A('couriers.suspend', { audit: 'admin+identity' }),
  'POST admin/deliveries/:id/dispute/resolve': A('deliveries.disputes.resolve', { ...MONEY, audit: 'admin+identity+ledger' }),
  'POST admin/couriers/:id/revoke': A('couriers.suspend', { audit: 'admin+identity' }),
  'GET admin/admins': A('admin.roles.read'),
  'POST admin/admins/:id/roles': A('admin.roles.manage', { audit: 'identity', note: 'maker-checker (admin_role_grant)' }),
  'POST admin/admins/:id/roles/:subId/revoke': A('admin.roles.manage', { audit: 'identity', note: 'protective: single operator' }),
  'GET admin/approvals': A('approvals.read'),
  'POST admin/approvals/:id/approve': A(null, { audit: 'identity', note: 'approve permission depends on the action' }),
  'POST admin/approvals/:id/reject': A(null, { audit: 'identity', note: 'approver or requester' }),
  'GET admin/identity-events': A('audit.read'),
  'GET admin/money/lookup': A('money.transactions.read', { note: 'read-only stage of any reference; cannot change balances' }),
  'GET admin/money/limits-usage': A('finance.position.read', { note: 'D15 maker-checker threshold calibration' }),
  'GET admin/businesses/lookup': A('businesses.read', { note: 'read-only: verification, settlement, staff + authority history, order/charge/refund states' }),
  'POST admin/businesses/:id/verification': A('merchants.verify', { audit: 'identity', note: 'operator cannot verify own business' }),
  'POST admin/businesses/:id/status': A('businesses.suspend', { audit: 'identity', note: 'J6.0: suspended / closed business is refused as a settlement target' }),
};

/** Route-auth kind the router uses for a policy actor. */
export function expectedRouterAuth(policy) {
  if (policy.actor === 'user') return 'user';
  if (policy.actor === 'admin') return 'admin';
  return 'public';
}
