#!/usr/bin/env node
/**
 * Render the J3 permission matrix (lib/authz/route-policy.js) and the
 * operator role → permission table to docs/JOKKO-J3-PERMISSION-MATRIX.md.
 *   node scripts/authz-matrix.mjs
 * The source of truth is the code; this document is generated from it.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

process.env.DATABASE_URL ??= 'postgres://render@localhost/none';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { ROUTE_POLICY } = await import('../lib/authz/route-policy.js');
const { ADMIN_ROLES, ADMIN_ROLE_CONFLICTS, USER_ROLES, BUSINESS_CAPABILITIES, LIMITS } = await import('../lib/authz/catalog.js');
const { APPROVAL_ACTIONS } = await import('../lib/authz/approvals.js');

const esc = (v) => String(v ?? '').replace(/\|/g, '\\|');
const groups = {};
for (const [k, p] of Object.entries(ROUTE_POLICY)) {
  const g = p.actor === 'admin' ? 'Operator console' : p.actor === 'user' ? `User — ${k.split(' ')[1].split('/')[0]}` : `${p.actor[0].toUpperCase()}${p.actor.slice(1)}`;
  (groups[g] ??= []).push([k, p]);
}

let md = `# Jokko J3: permission matrix (generated)

Generated by \`node scripts/authz-matrix.mjs\` from \`lib/authz/route-policy.js\` and \`lib/authz/catalog.js\`. Do not edit by hand.

The dispatcher (\`lib/authz/enforce.js\`) enforces centrally, before any handler runs:
- the actor;
- the operator permission;
- the active role;
- the cash-out and sensitive-change guards.

Handlers and services enforce the object-level \`resource\` relationship. \`tests/sweep\` proves this for every GET route and every mutating route that takes an id.

**${Object.keys(ROUTE_POLICY).length} routes.** Column legend:
- **KYC:** minimum effective tier.
- **Step-up:**
  - \`amount\` = PIN at or above 50 000 XOF, or for any amount from an untrusted session;
  - \`always\` = PIN in this session.
- **Risk:** the central guard class.
- **Audit:** where the action is recorded.

`;
for (const g of Object.keys(groups).sort()) {
  md += `\n## ${g}\n\n| Route | Actor | Permission | Resource relationship | Role | KYC | Step-up | Risk | Audit | Note |\n|---|---|---|---|---|---|---|---|---|---|\n`;
  for (const [k, p] of groups[g]) {
    md += `| \`${esc(k)}\` | ${p.actor} | ${esc(p.perm ?? '(authenticated)')} | ${esc(p.resource)} | ${esc(p.role)} | ${esc(p.tier)} | ${esc(p.stepUp)} | ${esc(p.risk)} | ${esc(p.audit)} | ${esc(p.note)} |\n`;
  }
}
md += `\n## Operator roles → permissions\n\n| Role | Permissions |\n|---|---|\n`;
for (const [r, perms] of Object.entries(ADMIN_ROLES)) md += `| \`${r}\` | ${perms.map((p) => `\`${p}\``).join(', ')} |\n`;
md += `\n**Separation-of-duty conflicts:** these pairs can never be held by one operator.\n\n`;
md += ADMIN_ROLE_CONFLICTS.map(([a, b]) => `- \`${a}\` × \`${b}\``).join('\n') + '\n';
md += `\n## Maker-checker actions\n\n| Action | Request permission | Approve permission |\n|---|---|---|\n`;
for (const [a, d] of Object.entries(APPROVAL_ACTIONS)) md += `| \`${a}\` | \`${d.requestPermission}\` | \`${d.approvePermission}\` |\n`;
md += `\n**Single-operator ceilings** (decision D10):\n- money adjustments ≤ ${LIMITS.adjustmentSingleMaxKori()} ₭, platform accounts only;\n- refunds ≤ ${LIMITS.refundSingleMaxKori()} ₭;\n- agent float ≤ ${LIMITS.agentFloatSingleMaxXof()} XOF.\n\nAbove a ceiling, the action needs a second operator.\n`;
md += `\n## Account roles\n\n| Role | How it becomes active | Approver permission |\n|---|---|---|\n`;
for (const [r, d] of Object.entries(USER_ROLES)) md += `| \`${r}\` | ${d.grant} | ${d.approver ? `\`${d.approver}\`` : '—'} |\n`;
md += `\n## Business capabilities\n\nThe owner (\`Business.ownerId\`) holds every capability. Members hold a capability only while their membership is ACTIVE.\n\n| Capability | Member roles |\n|---|---|\n`;
for (const [c, roles] of Object.entries(BUSINESS_CAPABILITIES)) md += `| \`${c}\` | ${roles.join(', ')} |\n`;
md += `\nOnly the owner may grant \`owner\`, \`admin\`, \`cfo\` or \`ceo\`. Nobody may grant a role above their own level.\n`;

writeFileSync(join(root, 'docs', 'JOKKO-J3-PERMISSION-MATRIX.md'), md);
console.log(`wrote docs/JOKKO-J3-PERMISSION-MATRIX.md (${Object.keys(ROUTE_POLICY).length} routes)`);
